---
title: "about_ema"
author: "Mikhail Balyasin"
date: "March 21, 2016"
output: html_document
---

### Erasmus Mundus Students and Alumni Association

EMA was established in 2006 at the initiative of the Directorate General for Education and Culture of the European Commission. The Association was driven by the Erasmus Mundus students from the very start developing into a dynamic and democratic organisation. 

In October 2006 the first EMA Liaison Group has met to decide on the statute of the Association, its logo and structure. The Association was ever since goverened by the Steering Committee, a motivated group of dedicated volunteers. 

In 2007 the Service Provider for EMA was selected, providing the technical and organisational support to the Association.

In October 2007 the first General Assembly of EMA took place in Brussels, having turned into an annual main event of the Association later hosted by the universities in Perugia, Vilnius, Madrid, Budapest and Prague. 

In 2008 a first regional chapter of EMA in India was formed, the other regions followed and by 2012 EMA regional chapters family is complete.

In 2010 EMA members voted on changing the initial structure of the Association. Four service teams are formed, professional networks are emerging at members' initiatives. Social initiatives followed: in 2011 EMA LGBT network was formed and EMA Women was created in 2012. 
