---
title: "about"
author: "Mikhail Balyasin"
date: "March 8, 2016"
output: html_document
---

### Course Quality of Student Services survey
This is the **second edition** of CQSS survey. The current edition of the survey brings a number of improvements. Many of these **improvements resulted d from the feedback of the EMJMD consortia** and **Erasmus Mundus students**. At the recommendation of EMJMD consortia, the course reports now include **comparative information** about each course in relation to the other EMJMD courses that received a sufficient number of responses. At the suggestion of survey respondents, the 2015 CQSS survey edition was released at the end of the academic year, to ensure that all respondents completed at least two EMJMD semesters before evaluating their experience. Additional changes have been made to the 2015 edition of the CQSS survey to streamline the survey experience, to facilitate the data analysis process, and to capture information about key subpopulations among EMJMD students.  For further reference, a **full description of the methodology** behind the creation of the 2015 edition of the CQSS survey and the analysis procedures behind the CQSS reports was published in the first 2016 edition of the academic journal 
