---
title: "acknowledgments"
author: "Mikhail Balyasin"
date: "March 8, 2016"
output: html_document
---

### Acknowledgments

The work of CQAB would not exist and could not continue **without the support of numerous committed volunteers spread all across the world**, driven by a strong motivation to help improve the quality of EMJMD courses. During the last 18 months, over 40 volunteers were involved with different stages of the CQSS project, from analyzing feedback received following the 2013 edition of the CQSS survey, to coding qualitative data and interpreting descriptive graphical information. **CQAB is grateful, humbled and proud to have supported the CQSS project fully through volunteer work**.

**Georgiana Mihut** was responsible for the challenging task of coordinating the 40 CQAB volunteers, including chairing most online meetings and manage all the needs, problems and troubles that arise from such a diverse group working on a very demanding task. She led and organized all major steps and tasks during the re-design, implementation and analysis of the survey.

**Mikhail Balyasin** is responsible for the substantial improvements to the design and content of course reports. He has skilfully generated the graphical information made available in the reports, and created the CQSS interactive online platform. **Luis Carvalho** coordinated the process of analyzing the vast qualitative data that emerged from the CQSS survey, rethought the architecture of the CQSS survey and helped streamline the survey experience for respondents. **Waqas Ahmed** kindly provided ongoing support with tasks that needed a last minute volunteer. **Patrik Punco** and **Haneen Deeb** worked tirelessly to create the online version of the CQSS survey, and became SurveyMonkey experts in the process. Additionally, **Hannen** was involved in the process of restructuring the survey together with Luis. The new version of the CQSS survey benefited from the proofreading skills of **Tugce Schmitt** and **Chiara Dalla Libera**. **Chiara** also facilitated our internal communication before the creation of a communication team. **Kristina Jaksa, Zhanna Saidenova, Sayeeda Amber Sayed, Rediet Tesfaye** and **Hacer Tarcanli** brought an invaluable contribution to the analysis of the qualitative data emerging from the 2015 CQSS survey. The qualitative analysis was far from being a simple task, and their attention to detail, team effort and systematic approach under the coordination of **Luis** serve as an exemplar of large data set qualitative analysis.

In the fall of 2015, CQAB conducted a new recruitment process to consolidate its volunteer basis. The new CQAB members provided invaluable contributions towards finalizing the products emerging from the CQSS survey, including the 78 course reports CQAB generated this year. **Aferdita Pustina, Eias Hausen, Felix Donkor, Jacob Sydenham, Joanna Dziadkowiec, Marsela Giovani Husen, Mattia Gusella, Pouneh Eftekhari, Rishikesh Ganjwe, Thuy Van Truong, Tiana Vekic, Tijana Maksimovic, Ana Godonoga, Bishnu Sarker, Chengjia Wang, Daniel Prasetyo, Elizabeth Humberstone, Habtamu Diriba Garomssa, Kseniia Goroshko, Nuoya Chen, Xinyu Wang,** and **Sonja Song** interpreted  the numerous graphs that emerged for each course from the quantitative analysis of the CQSS survey.

**Muhammad Sohaib Aslam, Wei Wang, Wenjie Shi,** and **Yemi Adeyeye**, members of the newly formed CQAB Communication Team provided support on communication tasks, proofreading and more. **Grischa Fraumann** and **Catherine Lourdes Dy** also provided proofreading help.

You can learn more about us [here](https://docs.google.com/document/d/1ipTxCHaPQhMLQRiSiFwKR2I9Wkxtv2XZGCkCHLk9eFg/edit?usp=sharing)!

CQAB is grateful for the ongoing support received from the **Erasmus Mundus Student and Alumni Association, and its leadership structures**. We are indebted to representatives of the **European Commission**, and **EMJMD course coordinators** whom we consider allies in a joint quest of improving the excellence brand of EMJMDs.
